---
title: "Which States are the Safest?"
author: "Raul G Lopez"
output:
  html_document:
    df_print: paged
---

```{r Load_Packages}

### Load the packages necessary
library(tidyverse)
library(dslabs)
data(murders)

```

```{r Max_population}

#### The name of the state with the maximum population is found by doing the following

murders$state[which.max(murders$population)]

```

```{r Murder_rate}

#### How to obtain the murder rate per capita

murder_rate <- murders$total / murders$population * 100000

```

```{r Ordering_by_rate}
#### Ordering the states by murder rate, in decreasing order

murders$state[order(murder_rate, decreasing=TRUE)]

```

```{r Define_rate_again}
####Defining murder rate as before

murder_rate <- murders$total / murders$population * 100000

#### Creating a logical vector that specifies if the murder rate in that state is less than or equal to 0.71

index <- murder_rate <= 0.71

```

```{r Calculating_how_many_states_less_0.71}

#### Calculating how many states have a murder rate less than or equal to 0.71

sum(index)

```

```{r Which_states_less_0.71}

#### Determining which states have murder rates less than or equal to 0.71

murders$state[index]

```

```{r Create_two_logical_vectors}

#### Creating the two logical vectors representing our conditions
west <- murders$region == "West"
safe <- murder_rate <= 1

```

```{r Define_index}

#### Defining an index and identifying states with both conditions true

index <- safe & west
murders$state[index]

```

```{r}

x <- c(FALSE, TRUE, FALSE, TRUE, TRUE, FALSE)
which(x)    #### returns indices that are TRUE

```

```{r Murder_rate_Massachusetts}

#### To determine the murder rate in Massachusetts we may do the following
index <- which(murders$state == "Massachusetts")
index
murder_rate[index]

```

```{r}

#### To obtain the indices and subsequent murder rates of New York, Florida, Texas, we do:

index <- match(c("New York", "Florida", "Texas"), murders$state)
index
murders$state[index]
murder_rate[index]

```

```{r}

x <- c("a", "b", "c", "d", "e")
y <- c("a", "d", "f")
y %in% x

#### to see if Boston, Dakota, and Washington are states

c("Boston", "Dakota", "Washington") %in% murders$state

```

```{r}

####Load plot package
library(dplyr)

```

```{r Plots}

#### A histogram of murder rates
murders <- mutate(murders, rate = total / population * 100000)
hist(murders$rate)

#### Boxplots of murder rates by region
boxplot(rate~region, data = murders)

```
